retargeting:
  type: DexPilot
  urdf_path: Revo2/urdf/revo2_left_hand.urdf

  # Revo2 has 6 actuated DOFs. Distal joints are mimic joints in the URDF.
  wrist_link_name: "left_base_link"
  target_joint_names: [
    "left_thumb_metacarpal_joint",
    "left_thumb_proximal_joint",
    "left_index_proximal_joint",
    "left_middle_proximal_joint",
    "left_ring_proximal_joint",
    "left_pinky_proximal_joint",
  ]
  finger_tip_link_names: [
    "left_thumb_tip_link",
    "left_index_tip_link",
    "left_middle_tip_link",
    "left_ring_tip_link",
    "left_pinky_tip_link",
  ]

  scaling_factor: 1.0
  low_pass_alpha: 0.35

  project_dist: 0.03
  escape_dist: 0.03
